import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { QueryProvider } from "./providers/QueryProvider";
import AOSInit from "@/components/AOSInit"; // Import here ✅

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pranoy's First Next App",
  description: "Generated by create next app",
  keywords: ["Next.js", "React", "JavaScript", "bappa" , "pranoy"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <QueryProvider>
          <AOSInit />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
